watch: Avoid double-decoding in python3
Both iter_content and the first line of the loop in the
etcd3gw watch code were decoding the chunk received.

In python2, this works fine:
```
$ python2 -c "print(b'hello_world'.decode().decode('utf-8'))"
hello_world
```

In python3, it raises an AttributeError:
```
$ python3 -c "print(b'hello_world'.decode().decode('utf-8'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'str' object has no attribute 'decode'
```

Thus, etcd3gw's watch is broken in python3.  This commit
fixes it by only decoding the line once.

Signed-off-by: Tyler J. Stachecki <tstachecki@bloomberg.net>
Change-Id: I203574a1ef4996a43860350be59fbe208457562d
Closes-Bug: 1950517